[external]
build-requires = [
  "virtual:compiler/c",
  "virtual:compiler/cpp",
]

# Note that there are quite a few optional dependencies, but they aren't used
# unless environment variables are set. So we don't add them here for now.
