[external]
build-requires = [
  "dep:virtual/compiler/c",
  "dep:virtual/compiler/cxx",
  "dep:generic/make",
  "dep:generic/ninja",
  "dep:generic/pkg-config",
]

[tool.pyproject-external.cross-build-env-vars]
NINJA = "{build_prefix}/bin/ninja"
