[external]
build-requires = [
  "virtual:compiler/c",
  "virtual:compiler/cpp",
  "pkg:generic/cmake",
  "pkg:generic/ninja",  # note; not needed on Windows - TODO handle specifiers in py-show
]

host-requires = [
  "pkg:github/apache/arrow",
]

# PyArrow has many optional dependencies (see `PYARROW_WITH_*` env vars in
# setup.py), but a plain `pip install` defaults to not using those even if they
# are installed, so we don't list them here to keep the install of system
# dependencies leaner.
