[external]
build-requires = [
  "virtual:compiler/c",
  "virtual:compiler/cpp",
  "pkg:generic/cmake",
]

host-requires = [
  "pkg:github/apache/arrow",
]

# PyArrow has many optional dependencies (see `PYARROW_WITH_*` env vars in
# setup.py), but a plain `pip install` defaults to not using those even if they
# are installed, so we don't list them here to keep the install of system
# dependencies leaner.
[external.optional-build-requires]
extra = [
  "pkg:generic/make",
  "pkg:generic/ninja",
]
