name: Build wheels

on: [push]

defaults:
  run:
    shell: bash

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  with_external_metadata:
    if: "github.repository == 'rgommers/external-deps-build'"
    strategy:
      fail-fast: false
      matrix:
        platform:
          # [container image name, display-name, use-external]
          - ["archlinux:latest", "Arch", false]  # baseline
          - ["archlinux:latest", "Arch", true]
          - ["fedora:39", "Fedora", true]
          - ["archlinux:latest", "conda-forge", true]
        pkgdata:
          # [package-name, import-name]
          - [cryptography, cryptography]
          - [pyyaml, yaml]  # poor detection of libyaml, falls back to pure Python on conda-forge
          - [lxml, lxml]    # doesn't work, no pyproject.toml + absolute import in setup.py
          - [greenlet, greenlet]
          - [httptools, httptools]
          - [markupsafe, markupsafe]
          - [grpcio, grpc]  # doesn't work, no pyproject.toml + absolute import in setup.py
          - [sqlalchemy, sqlalchemy]
          - [wrapt, wrapt]
          - [protobuf, google.protobuf]
          - [charset_normalizer, charset_normalizer]  # falls back to pure Python on conda-forge
          - [pillow, PIL]
          - [cffi, cffi]
          - [frozenlist, frozenlist]
          - [multidict, multidict]
          - [coverage, coverage]
          - [yarl, yarl]
          - [aiohttp, aiohttp]  # doesn't build on Python 3.12 yet
          - [psutil, psutil]
          - [numpy, numpy]
          - [pandas, pandas]
          - [scipy, scipy]  # Failing on Fedora because no auto-detection of FlexiBLAS yet
          - [pyarrow, pyarrow]
          - [pynacl, nacl]
          - [psycopg2-binary, psycopg2]
          - [rpds-py, rpds]
          - [bcrypt, bcrypt]
          - [scikit-learn, sklearn]
          - [msgpack, msgpack]
          - [matplotlib, matplotlib]  # Failing on conda-forge, missing Freetype symbols.
          - [regex, regex]
          - [kiwisolver, kiwisolver]
          - [pydantic-core, pydantic_core]
          - [pyrsistent, pyrsistent]
          - [grpcio-tools, grpc]
          - [pycryptodomex, Cryptodome]
          - [google-crc32c, google_crc32c]
    runs-on: ubuntu-22.04
    container: ${{ matrix.platform[0] }}
    name: ${{ matrix.pkgdata[0] }}, ${{ matrix.platform[1] }}, ${{ matrix.platform[2] }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install system Python
        run: |
          if [[ ${{ matrix.platform[1] }} == "Fedora" ]]; then
            sudo dnf install -y python  # will install 3.12
          elif [[ ${{ matrix.platform[1] }} == "Arch" ]]; then
            pacman -Syu python sudo --noconfirm # will install 3.11
          elif [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            "${SHELL}" <(curl -L micro.mamba.pm/install.sh)
            ~/.local/bin/micromamba shell init -s bash -p ~/micromamba
            source ~/.bashrc
            cp .mambarc ~/.mambarc
            micromamba create -n cfenv python pip  # will install 3.12
          else
            echo 'Unsupported distro!'
          fi

      - name: Download and patch sdist
        if: ${{ matrix.platform[2] }}
        run: |
          if [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            source ~/.bashrc && micromamba activate cfenv
          else
            python -m venv venv
            source venv/bin/activate
          fi

          python -m pip install pypi_json distro typer rich
          python download_and_patch_sdist.py ${{ matrix.pkgdata[0]}}

      - name: Install external dependencies
        if: ${{ matrix.platform[2] }}
        run: |
          if [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            source ~/.bashrc && micromamba activate cfenv
          else
            source venv/bin/activate
          fi
          name=${{ matrix.pkgdata[0]}}

          # `py-show` is not a package yet, so define an alias
          shopt -s expand_aliases
          if [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            alias py-show="python py-show/pyshow/__init__.py --package-manager=micromamba"
          else
            alias py-show="python py-show/pyshow/__init__.py"
          fi

          py-show --external $name
          py-show --external --system-install-cmd $name
          $(py-show --external --system-install-cmd $name)

      - name: Build from sdist
        if: ${{ matrix.platform[2] }}
        run: |
          if [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            source ~/.bashrc && micromamba activate cfenv
          else
            source venv/bin/activate
          fi
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install sdist/amended_sdist.tar.gz -v

      - name: Build from PyPI, no external deps
        if: ${{ !matrix.platform[2] }}
        run: |
          python -m venv venv
          source venv/bin/activate
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install ${{ matrix.pkgdata[0] }} --no-binary ${{ matrix.pkgdata[0] }} -v

      - name: Import installed package
        run: |
          if [[ ${{ matrix.platform[1] }} == "conda-forge" ]]; then
            source ~/.bashrc && micromamba activate cfenv
          else
            source venv/bin/activate
          fi

          python -c "import ${{ matrix.pkgdata[1] }}"
