name: Build wheels

on: [push]

defaults:
  run:
    shell: bash

permissions:
  contents: read # to fetch code (actions/checkout)

jobs:
  no_external_metadata:
    if: false
    strategy:
      fail-fast: false
      matrix:
        pkgdata:
          # [package-name, import-name]
          - [cryptography, cryptography]
          - [pyyaml, yaml]
          - [lxml, lxml]
          - [greenlet, greenlet]
          - [httptools, httptools]
          - [markupsafe, markupsafe]
          - [grpcio, grpc]
          - [sqlalchemy, sqlalchemy]
          - [wrapt, wrapt]
          - [protobuf, google.protobuf]
          - [charset_normalizer, charset_normalizer]
          - [pillow, PIL]
          - [cffi, cffi]
          - [frozenlist, frozenlist]
          - [multidict, multidict]
          - [coverage, coverage]
          - [yarl, yarl]
          - [aiohttp, aiohttp]
          - [psutil, psutil]
          - [numpy, numpy]
          - [pandas, pandas]
          - [scipy, scipy]
          - [pyarrow, pyarrow]
    runs-on: ubuntu-22.04
    name: ${{ matrix.pkgdata[0] }}, Ubuntu (no-external)
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4.7.1
        with:
          python-version: '3.11'

      - name: Build from sdist
        run: |
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install ${{ matrix.pkgdata[0] }} --no-binary ${{ matrix.pkgdata[0] }} -v

      - name: Import installed package
        run: |
          python -c "import ${{ matrix.pkgdata[1] }}"

  with_external_metadata:
    if: false  # This is done - adding new packages separately
    strategy:
      fail-fast: false
      matrix:
        platform:
          # [container image name, display-name]
          - ["fedora:39", "Fedora"]
          - ["archlinux:latest", "Arch"]
        pkgdata:
          # [package-name, import-name]
          - [cryptography, cryptography]
          - [pyyaml, yaml]
          - [lxml, lxml]              # no pyproject.toml in sdist; doesn't work, absolute import in setup.py to setupinfo
          - [greenlet, greenlet]      # no pyproject.toml in sdist
          - [httptools, httptools]     # no pyproject.toml in sdist
          - [markupsafe, markupsafe]  # no pyproject.toml in sdist
          - [grpcio, grpc]            # no pyproject.toml in sdist; doesn't work, absolute import in setup.py to _metadata
          - [sqlalchemy, sqlalchemy]  # no pyproject.toml in sdist
          - [wrapt, wrapt]            # no pyproject.toml in sdist
          - [protobuf, google.protobuf]     # no pyproject.toml in sdist
          - [charset_normalizer, charset_normalizer]  # no pyproject.toml in sdist
          - [pillow, PIL]
          - [cffi, cffi]
          - [frozenlist, frozenlist]
          - [multidict, multidict]
          - [coverage, coverage]
          - [yarl, yarl]
          - [aiohttp, aiohttp]
          - [psutil, psutil]
          - [numpy, numpy]
          - [pandas, pandas]
          - [scipy, scipy]  # Failing on Fedora because no auto-detection of FlexiBLAS yet
          - [pyarrow, pyarrow]
    runs-on: ubuntu-22.04
    container: ${{ matrix.platform[0] }}
    name: ${{ matrix.pkgdata[0] }}, ${{ matrix.platform[1] }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install system Python
        run: |
          if [[ ${{ matrix.platform[1] }} == "Fedora" ]]; then
            sudo dnf install -y python  # will install 3.12
          elif [[ ${{ matrix.platform[1] }} == "Arch" ]]; then
            pacman -Syu python sudo --noconfirm # will install 3.11
          else
            echo 'Unsupported distro!'
          fi

      - name: Download and patch sdist
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install pypi_json distro typer rich
          python download_and_patch_sdist.py ${{ matrix.pkgdata[0]}}

      - name: Install external dependencies
        run: |
          source venv/bin/activate
          name=${{ matrix.pkgdata[0]}}
          shopt -s expand_aliases
          alias py-show="python py-show/pyshow/__init__.py"  # not a package yet
          py-show --external $name
          py-show --external --system-install-cmd $name
          $(py-show --external --system-install-cmd $name)

      - name: Build from sdist
        run: |
          source venv/bin/activate
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install sdist/amended_sdist.tar.gz -v

      - name: Import installed package
        run: |
          source venv/bin/activate
          python -c "import ${{ matrix.pkgdata[1] }}"


  beyond_top_100:
    strategy:
      fail-fast: false
      matrix:
        platform:
          # [container image name, display-name, use-external]
          - ["archlinux:latest", "Arch", false]  # baseline
          #- ["archlinux:latest", "Arch", true]
          #- ["fedora:39", "Fedora", true]
        pkgdata:
          # [package-name, import-name]
          - [pynacl, nacl]
          - [psycopg2-binary, psycopg2]
          - [rpds-py, rpds]
          - [bcrypt, bcrypt]
          - [scikit-learn, sklearn]
          - [msgpack, msgpack]
          - [matplotlib, matplotlib]
          - [regex, regex]
          - [kiwisolver, kiwisolver]
          - [pydantic-core, pydantic_core]
          - [pyrsistent, pyrsistent]
          - [grpcio-tools, grpc]
          - [pycryptodomex, Cryptodome]
          - [google-crc32c, google_crc32c]
    runs-on: ubuntu-22.04
    container: ${{ matrix.platform[0] }}
    name: ${{ matrix.pkgdata[0] }}, ${{ matrix.platform[1] }}
    steps:
      - uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608 # v4.1.0

      - name: Install system Python
        run: |
          if [[ ${{ matrix.platform[1] }} == "Fedora" ]]; then
            sudo dnf install -y python  # will install 3.12
          elif [[ ${{ matrix.platform[1] }} == "Arch" ]]; then
            pacman -Syu python sudo --noconfirm # will install 3.11
          else
            echo 'Unsupported distro!'
          fi

      - name: Download and patch sdist
        if: ${{ matrix.platform[2] }}
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install pypi_json distro typer rich
          python download_and_patch_sdist.py ${{ matrix.pkgdata[0]}}

      - name: Install external dependencies
        if: ${{ matrix.platform[2] }}
        run: |
          source venv/bin/activate
          name=${{ matrix.pkgdata[0]}}
          shopt -s expand_aliases
          alias py-show="python py-show/pyshow/__init__.py"  # not a package yet
          py-show --external $name
          py-show --external --system-install-cmd $name
          $(py-show --external --system-install-cmd $name)

      - name: Build from sdist
        if: ${{ matrix.platform[2] }}
        run: |
          source venv/bin/activate
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install sdist/amended_sdist.tar.gz -v

      - name: Build from PyPI, no external deps
        if: ${{ !matrix.platform[2] }}
        run: |
          python -m venv venv
          source venv/bin/activate
          # Dependencies may be installed from wheels, the target package from sdist
          python -m pip install ${{ matrix.pkgdata[0] }} --no-binary ${{ matrix.pkgdata[0] }} -v

      - name: Import installed package
        run: |
          source venv/bin/activate
          python -c "import ${{ matrix.pkgdata[1] }}"
